version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:12
    restart: always
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend:/app/:cached
    env_file:
      - ./.envs/.local/.app
    environment:
      PYTHONPATH: .
    depends_on:
      - "postgres"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
    environment:
      - NODE_ENV=development

volumes:
  db-data:
