"""Added building table

Revision ID: 37794074ade7
Revises: 91979b40eb38
Create Date: 2021-01-21 16:06:59.079140-08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37794074ade7'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
                    sa.Column('adressid', sa.Integer(), nullable=False),
                    sa.Column('objectid', sa.Integer(), nullable=True),
                    sa.Column('bez_name', sa.String(), nullable=True),
                    sa.Column('ort_name', sa.String(), nullable=True),
                    sa.Column('plr_name', sa.String(), nullable=True),
                    sa.Column('str_name', sa.String(), nullable=True),
                    sa.Column('hnr', sa.Integer(), nullable=True),
                    sa.Column('plz', sa.Integer(), nullable=True),
                    sa.Column('blk', sa.Integer(), nullable=True),
                    sa.Column('adr_datum', sa.Date(), nullable=True),
                    sa.Column('str_datum', sa.Date(), nullable=True),
                    sa.Column('qualitaet', sa.String(), nullable=True),
                    sa.Column('typ', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('adressid')
                    )
    op.create_index(op.f('ix_building_adressid'), 'building', ['adressid'], unique=True)
    op.create_index(op.f('ix_building_objectid'), 'building', ['objectid'], unique=False)
    op.create_index(op.f('ix_building_plz'), 'building', ['plz'], unique=False)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.drop_column('user', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.alter_column('user', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.alter_column('user', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.drop_index(op.f('ix_building_plz'), table_name='building')
    op.drop_index(op.f('ix_building_objectid'), table_name='building')
    op.drop_index(op.f('ix_building_adressid'), table_name='building')
    op.drop_table('building')
    # ### end Alembic commands ###
